### ISSUE TITLE
Allow grouping by recording group

### ISSUE THREAD

**Issue by mlg9000** [stuart-knock/myth2kodi#2]
It would be nice to be able to group recordings by recording group.  So for example instead of "tv/show/season/episode" you could do "recording group/tv/show/season/episode".  myth2kodi has lots of uses beyond just Kodi, and having this would allow you to group recording into different libraries (kids shows etc) either in Kodi (per user librarys) or in something like Plex where you have multiple libraries.

**Comment by stuart-knock** [comment]
To work for your use-case, would the "recording group" have to be at the place in the path that you mentioned?

That is, you've requested this:

    "recording group/tv/show/season/episode".

But, would enabling this:

    "tv/recording group/show/season/episode"

achieve what you have in mind for your use-case?

The reason I ask is that, with the current way things are done, the path consists of:
    
    <user-setting-part>/<auto-generated-part>

where the `<auto-generated-part>` for a tv episode is of the form:
      
    "show/season/episode"

and the `<user-setting-part>` for tv episodes would be something like:
    
    "/media/video/tv"

So, it should be a fairly simple change to enable `<auto-generated-part>` to optionally have the form:
    
    "recording group/show/season/episode"

whereas it'd require more significant changes to enable exactly what you asked for.

**Comment by mlg9000** [comment]
"tv/recording group/show/season/episode" would work just as well.  All that's needed is to sort shows (and movies etc) into different directories so that I can point different Plex libraries at each directory.

**Comment by mlg9000** [comment]
I've tested the changes you committed for this in 37fbe63 and they work without issue.  Thanks for adding this.
